import type { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "Classic Men's Suit",
    sku: "SUIT-001",
    category: "Men Collection",
    price: "$120.00",
    stock: 25,
    status: "Active",
    image: "/images/products/classic-suit.svg",
  },
  {
    id: 2,
    name: "Premium Kurta",
    sku: "KURTA-002",
    category: "Traditional Wear",
    price: "$65.00",
    stock: 12,
    status: "Active",
    image: "/images/products/premium-kurta.svg",
  },
  {
    id: 3,
    name: "Ladies Formal Dress",
    sku: "DRESS-003",
    category: "Women Collection",
    price: "$95.00",
    stock: 0,
    status: "Out of Stock",
    image: "/images/products/formal-dress.svg",
  },
  {
    id: 4,
    name: "Cotton Fabric (1 Meter)",
    sku: "FAB-004",
    category: "Fabrics",
    price: "$12.00",
    stock: 50,
    status: "Active",
    image: "/images/products/fabric.svg",
  },
  {
    id: 5,
    name: "Kids Shalwar Kameez",
    sku: "KID-005",
    category: "Kids Collection",
    price: "$45.00",
    stock: 8,
    status: "Low Stock",
    image: "/images/products/kids.svg",
  },
];
